name: MicroHs-CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: 0 0 * * *
jobs:
  linux:
    name: MicroHs-CI - Linux
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mcabal-${{ github.sha }}
        path: ~/.mcabal/mhs-*
        restore-keys: ${{ runner.os }}-mcabal
    - uses: sol/setup-MicroHs@nightly
    - name: checkout QuickCheck repo
      uses: actions/checkout@v4
    - name: build QuickCheck
      run: mcabal -r build
    - name: test QuickCheck
      run: ./test-mhs
