name: MicroHs-CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: 0 0 * * *
jobs:
  linux:
    name: MicroHs-CI - Linux
    runs-on: ubuntu-24.04
    steps:
    - uses: sol/setup-MicroHs@add-setup-action
    - name: checkout QuickCheck repo
      uses: actions/checkout@v4
    - name: build QuickCheck
      run: mcabal -r build
    - name: test QuickCheck
      run: ./test-mhs
