name: MicroHs-CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: 0 0 * * *
jobs:
  linux:
    name: MicroHs-CI - Linux
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mcabal-${{ github.sha }}
        path: ~/.mcabal/mhs-*
        restore-keys: ${{ runner.os }}-mcabal
    - name: checkout mhs repo
      uses: actions/checkout@v4
      with:
        repository: augustss/MicroHs
        path: mhs
    - name: make and install mhs
      run: |
        cd mhs
        make minstall
    - name: checkout QuickCheck repo
      uses: actions/checkout@v4
    - name: build QuickCheck
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        mcabal -r build
    - name: test QuickCheck
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        ./test-mhs
